In [10]:
import pandas as pd

In [245]:
df = pd.read_csv("popular_shows_dataset.csv")
pd.set_option("display.max_row",None)
pd.set_option("display.max_column",None)
df.head()

              title  year   revenue     imdb_id  tmdb_id  trakt_id
0           Hoppers  2026  29000000  tt26443616  1327819   1085761
1  Reminders of Him  2026  18000000  tt33714084  1367642   1116720
2         undertone  2026   9300000  tt35892608  1480387   1213506
3          Scream 7  2026   8400000  tt27047903  1159559    934134
4              GOAT  2026   4700000  tt27613895  1297842   1057839

In [228]:
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     1000 non-null   object
 1   year      1000 non-null   int64
 2   revenue   1000 non-null   int64
 3   imdb_id   1000 non-null   object
 4   tmdb_id   1000 non-null   int64
 5   trakt_id  1000 non-null   int64
dtypes: int64(4), object(2)
memory usage: 47.0+ KB

title       0
year        0
revenue     0
imdb_id     0
tmdb_id     0
trakt_id    0
dtype: int64

In [230]:
df.shape

(1000, 6)

In [231]:
df.describe()

              year       revenue       tmdb_id      trakt_id
count  1000.000000  1.000000e+03  1.000000e+03  1.000000e+03
mean   2018.800000  7.750000e+06  1.029867e+06  8.375175e+05
std      14.414152  8.705877e+06  5.195836e+05  4.246083e+05
min    1989.000000  1.100000e+06  1.497000e+03  9.910000e+02
25%    2026.000000  1.700000e+06  1.159559e+06  9.341340e+05
50%    2026.000000  3.400000e+06  1.234494e+06  1.000940e+06
75%    2026.000000  9.300000e+06  1.327819e+06  1.085761e+06
max    2026.000000  2.900000e+07  1.480387e+06  1.213506e+06

In [248]:
df["title"] = df["title"].astype(str).str.lower().str.replace('"', '', regex=False).str.replace('!', '', regex=False)
df["title"] = df["title"].str.title().str.replace(r"\bIi\b", "II", regex=True)
df["title"].head()

0             Hoppers
1    Reminders Of Him
2           Undertone
3            Scream 7
4                Goat
Name: title, dtype: object

In [249]:
#cleaning title column

df["title"].value_counts(dropna=False)

title
Hoppers                                                    100
Reminders Of Him                                           100
Undertone                                                  100
Scream 7                                                   100
Goat                                                       100
The Bride                                                  100
Kiki'S Delivery Service                                    100
Wuthering Heights                                          100
Teenage Mutant Ninja Turtles II: The Secret Of The Ooze    100
Crime 101                                                  100
Name: count, dtype: int64

In [217]:
#df.nunique()

In [250]:
#clean year column 

df["year"].value_counts(dropna=False)

year
2026    800
1989    100
1991    100
Name: count, dtype: int64

In [251]:
df["revenue"] = df["revenue"].astype(float)

In [218]:
df["revenue"].value_counts(dropna=False)

revenue
1700000     200
1500000     200
29000000    100
18000000    100
9300000     100
8400000     100
4700000     100
2100000     100
1100000     100
Name: count, dtype: int64

In [252]:
df["revenue"] = df["revenue"].astype(str).str.strip()
df["revenue"] = pd.to_numeric(df["revenue"],errors = "coerce")
df["revenue"].head()

0    29000000.0
1    18000000.0
2     9300000.0
3     8400000.0
4     4700000.0
Name: revenue, dtype: float64

In [196]:
df["imdb_id"].value_counts(dropna=False)

imdb_id
tt0103060     200
tt26443616    100
tt33714084    100
tt35892608    100
tt27047903    100
tt27613895    100
tt30851137    100
tt0097814     100
tt32897959    100
tt32430579    100
Name: count, dtype: int64

In [253]:
df["imdb_id"] = df["imdb_id"].astype(str).str.extract(r"(\d+)")
df["imdb_id"] = "tt" + df["imdb_id"].str.zfill(9)
df["imdb_id"].head()

0    tt026443616
1    tt033714084
2    tt035892608
3    tt027047903
4    tt027613895
Name: imdb_id, dtype: object

In [255]:
df["tmdb_id"].value_counts(dropna=False)

tmdb_id
0001327819    100
0001367642    100
0001480387    100
0001159559    100
0001297842    100
0001159831    100
0000016859    100
0001316092    100
0000001497    100
0001171145    100
Name: count, dtype: int64

In [254]:
df["tmdb_id"] = df["tmdb_id"].astype(str).str.strip().str.extract(r"(\d+)")
df["tmdb_id"] = df["tmdb_id"].str.zfill(10)
df["tmdb_id"].head()

0    0001327819
1    0001367642
2    0001480387
3    0001159559
4    0001297842
Name: tmdb_id, dtype: object

In [171]:
df["trakt_id"].value_counts(dropna=False)

trakt_id
00000000991    200
00001085761    100
00001116720    100
00001213506    100
00000934134    100
00001057839    100
00000934595    100
00000010314    100
00001077273    100
00000944042    100
Name: count, dtype: int64

In [256]:
df["trakt_id"] = df["trakt_id"].astype(str).str.strip().str.extract(r"(\d+)")
df["trakt_id"] = df["trakt_id"].str.zfill(11)
df["trakt_id"].head()

0    00001085761
1    00001116720
2    00001213506
3    00000934134
4    00001057839
Name: trakt_id, dtype: object

In [257]:
df.shape

(1000, 6)

In [259]:
df.isna().sum()

title       0
year        0
revenue     0
imdb_id     0
tmdb_id     0
trakt_id    0
dtype: int64

In [260]:
df.duplicated().sum()

np.int64(990)

In [273]:
df.value_counts().head(10)

title                                                    year  revenue     imdb_id      tmdb_id     trakt_id
Crime 101                                                2026  1100000.0   tt032430579  0001171145  00000944042    1
Goat                                                     2026  4700000.0   tt027613895  0001297842  00001057839    1
Hoppers                                                  2026  29000000.0  tt026443616  0001327819  00001085761    1
Kiki'S Delivery Service                                  1989  1700000.0   tt000097814  0000016859  00000010314    1
Reminders Of Him                                         2026  18000000.0  tt033714084  0001367642  00001116720    1
Scream 7                                                 2026  8400000.0   tt027047903  0001159559  00000934134    1
Teenage Mutant Ninja Turtles II: The Secret Of The Ooze  1991  1500000.0   tt000103060  0000001497  00000000991    1
The Bride                                                2026  2100000.0   tt030851137  0001159831  00000934595    1
Undertone                                                2026  9300000.0   tt035892608  0001480387  00001213506    1
Wuthering Heights                                        2026  1700000.0   tt032897959  0001316092  00001077273    1
Name: count, dtype: int64

In [269]:
df = df.drop_duplicates()

In [274]:
df.shape

(10, 6)

In [275]:
df.to_csv("Movie Dataset Exploratory Data Analysis.csv", index=False)

Conclusion
- Dataset contained duplicate records
- After cleaning only 10 unique movies remained
- Data quality was poor but useful for learning EDA process